# Generated by Django 3.2.5 on 2021-08-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
        ('bid', '0002_alter_userbid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbid',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_login.bids', unique=True, verbose_name='bid'),
        ),
        migrations.AlterField(
            model_name='userbid',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_login.profile', verbose_name='profile'),
        ),
    ]
