# Generated by Django 3.2.5 on 2021-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_auto_20210809_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbid',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('compelete', 'compelete')], max_length=200, null=True),
        ),
    ]
