# Generated by Django 3.2.5 on 2021-08-08 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state')),
                ('published', models.CharField(blank=True, max_length=255, null=True, verbose_name='published')),
                ('end', models.CharField(blank=True, max_length=255, null=True, verbose_name='closed')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('short_intro', models.TextField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField()),
                ('profiel_image', models.ImageField(blank=True, default='images/banner.png', null=True, upload_to='images/')),
                ('social_facebook', models.URLField(blank=True, null=True)),
                ('social_twitter', models.URLField(blank=True, null=True)),
                ('social_github', models.URLField(blank=True, null=True)),
                ('social_website', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
